
engine:
  max_urls: 100

files:
  crawled_file: "crawled.txt"
  to_crawl_file: "to_crawl.txt"
  graph_file: "graph"
  titles_file: "titles"
  page_rank_file: "ranks"
  logger_file: "logfile.log"

database:
  db_name: "development"

crawler:
  user_agent: "lambda-crawler"
